---
- name: Testing Tags
  hosts: all
  become: yes
  # gather_facts: yes
  tasks:
    - ansible.builtin.debug:
        msg: "Trying to Install Git on Ubuntu"
      tags:
        - debug
    - name: Install Git
      ansible.builtin.package:
        name: git
        # become: yes
      tags:
        - Git Installation
    - ansible.builtin.debug:
        msg: "Git Successfully Installed"
      tags:
        - debug